// Code generated by "enumer -type=FeedbackType"; DO NOT EDIT
/*

SPDX-Copyright: Copyright (c) Capital One Services, LLC
SPDX-License-Identifier: Apache-2.0
Copyright 2017 Capital One Services, LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and limitations under the License.

*/
package model

import (
	"encoding/json"
	"fmt"
)

// FeedbackType is an enum.
// It is serialized as a string in JSON and as an integer in SQL.

// FeedbackType enum maps.
var (
	strMapFeedbackType = map[string]FeedbackType{
		"comment": CommentType,
		"review":  ReviewType,
	}

	intMapFeedbackType = map[FeedbackType]string{
		CommentType: "comment",
		ReviewType:  "review",
	}
)

// Known says whether or not this value is a known enum value.
func (s FeedbackType) Known() bool {
	_, ok := intMapFeedbackType[s]
	return ok
}

// String is for the standard stringer interface.
func (s FeedbackType) String() string {
	return intMapFeedbackType[s]
}

// UnmarshalJSON satisfies the json.Unmarshaler
func (s *FeedbackType) UnmarshalJSON(data []byte) error {
	str := ""
	err := json.Unmarshal(data, &str)
	if err != nil {
		return err
	}
	var ok bool
	*s, ok = strMapFeedbackType[str]
	if !ok {
		return fmt.Errorf("Unknown FeedbackType enum value: %s", str)
	}
	return nil
}

// MarshalJSON satisfies the json.Marshaler
func (s FeedbackType) MarshalJSON() ([]byte, error) {
	if !s.Known() {
		return nil, fmt.Errorf("Unknown FeedbackType enum value: %d", int(s))
	}
	name := intMapFeedbackType[s]
	return json.Marshal(name)
}
