language: go
go:
  - "1.10.x"

install:
  - go get -u github.com/golang/dep
  - go install github.com/golang/dep/cmd/dep
  - export PATH=$GOPATH/bin:$PATH
  - dep ensure -v -vendor-only
  - dep status

script: make test
